# Generated by Django 6.0.6 on 2026-07-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('component_type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich Text'), ('image', 'Image'), ('gallery', 'Gallery'), ('statistics', 'Statistics'), ('cta', 'Call To Action'), ('faq', 'FAQ'), ('team', 'Team'), ('partners', 'Partners'), ('video', 'Video'), ('contact_form', 'Contact Form'), ('donation', 'Donation'), ('custom_html', 'Custom HTML')], max_length=30)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pages.page')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
    ]
