# Generated by Django 6.0.6 on 2026-07-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecomponent',
            old_name='button_text',
            new_name='secondary_button_text',
        ),
        migrations.RenameField(
            model_name='pagecomponent',
            old_name='button_url',
            new_name='secondary_button_url',
        ),
        migrations.RemoveField(
            model_name='pagecomponent',
            name='configuration',
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='enable_animation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='hero_height',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('fullscreen', 'Full Screen')], default='large', max_length=20),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='overlay_color',
            field=models.CharField(default='rgba(0,0,0,0.55)', max_length=20),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=55),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
    ]
