# Generated by Django 6.0.6 on 2026-07-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_button_text_pagecomponent_secondary_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecomponent',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='components/backgrounds/'),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='button_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagecomponent',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='hero_height',
            field=models.CharField(choices=[('small', 'Small (400px)'), ('medium', 'Medium (600px)'), ('large', 'Large (800px)'), ('fullscreen', 'Full Screen')], default='large', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='overlay_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagecomponent',
            name='text_alignment',
            field=models.CharField(choices=[('start', 'Left'), ('center', 'Center'), ('end', 'Right')], default='center', max_length=20),
        ),
    ]
