# Generated by Django 6.0.6 on 2026-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_pagecomponent_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecomponent',
            name='overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
