# Generated by Django 6.0.6 on 2026-07-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Internal path or external URL', max_length=255)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.menuitem')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
