# Generated by Django 6.0.6 on 2026-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('location', 'display_order')},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='css_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: fa-solid fa-house', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='location',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('mobile', 'Mobile')], default='header', max_length=20),
        ),
    ]
