# Generated by Django 6.0.6 on 2026-07-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_page_options_page_display_order_page_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
